### ISSUE TITLE
Hardcoded API Key

### ISSUE THREAD

**Issue by carolynrehm** [Finance-Portfolio-Manager/API#3]
https://github.com/Finance-Portfolio-Manager/API/blob/12db6a9d3ac960a593e475edd784091dbca098de/src/main/java/dev/team4/portfoliotracker/controllers/ApiController.java#L52

![](https://c.tenor.com/cQWXNFB5bkwAAAAC/no-dramatic.gif)

**Comment by Sife-ops** [comment]
done
